version: 0.2
env:
  git-credential-helper: yes
  variables:
    ECR_REPOSITORY_NAME: "yojee-solver"
    IMAGE_NAME: "yojee-vroom"

phases:
 pre_build:
  commands:
    - REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME --output text --query repositories[0].repositoryUri)
    - DOCKER_TAG=$REPOSITORY_URI:$IMAGE_NAME-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - LATEST_DOCKER_TAG=$REPOSITORY_URI:$IMAGE_NAME-latest
    - $(aws ecr get-login --no-include-email)
    - echo $DOCKER_TAG > imagedefinition.txt
    - docker pull $LATEST_DOCKER_TAG || true
 build:
   commands:      
      - git submodule update --init --recursive
      - docker build --cache-from="$LATEST_DOCKER_TAG" --tag "$DOCKER_TAG" --tag "$LATEST_DOCKER_TAG" .
      - docker push --all-tags $REPOSITORY_URI

artifacts:
  files:
    - 'imagedefinition.txt'
